package org.gcube.dataanalysis.ecoengine.configuration;

public enum ALG_PROPS {
	
		PARALLEL_SPECIES_VS_CSQUARE_FROM_DATABASE,
		SPECIES_VS_CSQUARE_FROM_DATABASE,
		SPECIES_VS_CSQUARE_REMOTE_FROM_DATABASE,
		SPECIES_VS_CSQUARE,
		PHENOMENON_VS_GEOINFO,
		SPECIES_ENVELOPES,
		SPECIES_MODEL,
		PHENOMENON_VS_PARALLEL_PHENOMENON
}
