package org.gcube.portlets.user.td.expressionwidget.shared.model;

/**
 * 
 * @author giancarlo
 * email: <a href="mailto:g.panichi@isti.cnr.it">g.panichi@isti.cnr.it</a> 
 *
 */
public enum C_OperatorType {
	// Arithmetic
	ADDITION, SUBTRACTION, MULTIPLICATION, DIVISION, MODULUS, EXPONENTIATION,

	// COMPARISON

	EQUALS, GREATER, LESSER,

	GREATER_OR_EQUALS, LESSER_OR_EQUALS,

	NOT_EQUALS, NOT_GREATER, NOT_LESSER,

	// LOGICAL

	ALL, AND, ANY, BETWEEN, NOT_BETWEEN, EXISTS, IN, NOT_IN, LIKE, NOT_LIKE, NOT, OR, IS_NULL, UNIQUE, IS_NOT_NULL,

	// AGGREGATION
	AVG, COUNT, MAX, MIN, SUM, ST_EXTENT,

	// STRING

	BEGINS_WITH, ENDS_WITH, CONTAINS, MATCH_REGEX,

	NOT_BEGINS_WITH, NOT_ENDS_WITH, NOT_CONTAINS, NOT_MATCH_REGEX,

	CONCAT, SUBSTRING_BY_INDEX, SUBSTRING_BY_REGEX, SUBSTRING_POSITION, TEXT_REPLACE_MATCHING_REGEX,

	TRIM, LENGTH, UPPER, LOWER,

	MD5, SOUNDEX, SIMILARITY, LEVENSHTEIN,

	// FUNCTIONS
	CAST,

	// COMPLEX

	SELECT_IN;

}
