/**
 * 
 */
package org.gcube.portlets.user.td.widgetcommonevent.client.type;

/**
 * 
 * @author "Giancarlo Panichi" 
 * <a href="mailto:g.panichi@isti.cnr.it">g.panichi@isti.cnr.it</a> 
 *
 */
public enum WidgetRequestType {
	CHANGECOLUMNTYPEPANEL,
	POSITIONCOLUMNPANEL,
	ADDCOLUMNPANEL,
	DELETECOLUMNPANEL,
	SPLITCOLUMNPANEL,
	MERGECOLUMNPANEL,
	GROUPBYPANEL,
	TIMEAGGREGATIONPANEL,
	NORMALIZEPANEL,
	DENORMALIZEPANEL,
	LABELCOLUMNPANEL,
	CHANGETABLETYPEPANEL,
	DUPLICATESROWSDETECTIONPANEL,
	DUPLICATESROWSDELETEPANEL,
	VALIDATIONSTASKSPANEL,
	CURATIONBYREPLACEBATCHDIALOG,
	MONITORBACKGROUNDPANEL,
	RESOURCESPANEL,
	GEOSPATIALCREATECOORDINATESPANEL,
	GEOMETRYCREATEPOINTPANEL,
	DOWNSCALECSQUAREPANEL;
	
}
