package org.gcube.dataanalysis.ecoengine.datatypes.enumtypes;

public enum DatabaseParameters {
	
	DATABASEUSERNAME,
	DATABASEPASSWORD,
	DATABASEURL,
	DATABASEDRIVER,
	DATABASEDIALECT,
	DATABASETABLESPACE,
	REMOTEDATABASERRNAME,
	REMOTEDATABASEURL,
	REMOTEDATABASEUSERNAME,
	REMOTEDATABASEPASSWORD,
	REMOTEDATABASEDRIVER,
	REMOTEDATABASEDIALECT
	
}
