INSERT INTO Area VALUES('01','Africa - inland waters','FAO');
INSERT INTO Area VALUES('02','North America - inland waters','FAO');
INSERT INTO Area VALUES('03','South America - inland waters','FAO');
INSERT INTO Area VALUES('04','Asia - inland waters','FAO');
INSERT INTO Area VALUES('05','Europe - inland waters','FAO');
INSERT INTO Area VALUES('06','Oceania - inland waters','FAO');
INSERT INTO Area VALUES('07','Former USSR','FAO');
INSERT INTO Area VALUES('08','Antartica inland waters','FAO');
INSERT INTO Area VALUES('18','Arctic Sea','FAO');
INSERT INTO Area VALUES('21','Northwest Atlantic','FAO');
INSERT INTO Area VALUES('27','Northeast Atlantic','FAO');
INSERT INTO Area VALUES('31','Western Central Atlantic','FAO');
INSERT INTO Area VALUES('34','Eastern Central Atlantic','FAO');
INSERT INTO Area VALUES('37','Mediterranean and Black Sea','FAO');
INSERT INTO Area VALUES('41','Southwest Atlantic','FAO');
INSERT INTO Area VALUES('47','Southeast Atlantic','FAO');
INSERT INTO Area VALUES('48','Atlantic (Antarctic)','FAO');
INSERT INTO Area VALUES('51','Western Indian Ocean','FAO');
INSERT INTO Area VALUES('57','Eastern Indian Ocean','FAO');
INSERT INTO Area VALUES('58','Indian Ocean (Antarctic)','FAO');
INSERT INTO Area VALUES('61','Northwest Pacific','FAO');
INSERT INTO Area VALUES('67','Northeast Pacific','FAO');
INSERT INTO Area VALUES('71','Western Central Pacific','FAO');
INSERT INTO Area VALUES('77','Eastern Central Pacific','FAO');
INSERT INTO Area VALUES('81','Southwest Pacific','FAO');
INSERT INTO Area VALUES('87','Southeast Pacific','FAO');
INSERT INTO Area VALUES('88','Pacific ( Antarctic)','FAO');

INSERT INTO Area VALUES('8','Albania','EEZ');
INSERT INTO Area VALUES('12','Algeria','EEZ');
INSERT INTO Area VALUES('16','American Samoa','EEZ');
INSERT INTO Area VALUES('16','USA (American Samoa)','EEZ');
INSERT INTO Area VALUES('24','Angola','EEZ');
INSERT INTO Area VALUES('28','Antigua & Barbuda','EEZ');
INSERT INTO Area VALUES('32','Argentina','EEZ');
INSERT INTO Area VALUES('36','Australia','EEZ');
INSERT INTO Area VALUES('38','Australia (Lord Howe Isl.)','EEZ');
INSERT INTO Area VALUES('38','Lord Howe Isl. (Australia)','EEZ');
INSERT INTO Area VALUES('44','Bahamas','EEZ');
INSERT INTO Area VALUES('48','Bahrain','EEZ');
INSERT INTO Area VALUES('50','Bangladesh','EEZ');
INSERT INTO Area VALUES('52','Barbados','EEZ');
INSERT INTO Area VALUES('56','Belgium','EEZ');
INSERT INTO Area VALUES('60','Bermuda (UK)','EEZ');
INSERT INTO Area VALUES('60','UK (Bermuda)','EEZ');
INSERT INTO Area VALUES('70','Bosnia & Herzegovina','EEZ');
INSERT INTO Area VALUES('74','Bouvet Isl. (Norway)','EEZ');
INSERT INTO Area VALUES('74','Norway (Bouvet Isl.)','EEZ');
INSERT INTO Area VALUES('76','Brazil','EEZ');
INSERT INTO Area VALUES('77','Brazil (Trindade & Martin Vaz Isl.)','EEZ');
INSERT INTO Area VALUES('77','Trindade & Martin Vaz Isl. (Brazil)','EEZ');
INSERT INTO Area VALUES('84','Belize','EEZ');
INSERT INTO Area VALUES('86','Brit. Indian Ocean Terr. (UK)','EEZ');
INSERT INTO Area VALUES('86','UK (Brit. Indian Ocean Terr.)','EEZ');
INSERT INTO Area VALUES('90','Solomon Isl.','EEZ');
INSERT INTO Area VALUES('92','UK (Virgin Isl.)','EEZ');
INSERT INTO Area VALUES('92','Virgin Isl. (UK)','EEZ');
INSERT INTO Area VALUES('96','Brunei Darussalam','EEZ');
INSERT INTO Area VALUES('100','Bulgaria','EEZ');
INSERT INTO Area VALUES('104','Myanmar','EEZ');
INSERT INTO Area VALUES('111','Eritrea','EEZ');
INSERT INTO Area VALUES('116','Cambodia','EEZ');
INSERT INTO Area VALUES('120','Cameroon','EEZ');
INSERT INTO Area VALUES('124','Canada','EEZ');
INSERT INTO Area VALUES('132','Cape Verde','EEZ');
INSERT INTO Area VALUES('136','Cayman Isl. (UK)','EEZ');
INSERT INTO Area VALUES('136','UK (Cayman Isl.)','EEZ');
INSERT INTO Area VALUES('144','Sri Lanka','EEZ');
INSERT INTO Area VALUES('152','Chile','EEZ');
INSERT INTO Area VALUES('153','Chile (Easter Isl.)','EEZ');
INSERT INTO Area VALUES('153','Easter Isl. (Chile)','EEZ');
INSERT INTO Area VALUES('154','Chile (Desventuradas Isl.)','EEZ');
INSERT INTO Area VALUES('154','Desventuradas Isl. (Chile)','EEZ');
INSERT INTO Area VALUES('155','Chile (Juan Fernandez Isl.)','EEZ');
INSERT INTO Area VALUES('155','Juan Fernandez Isl. (Chile)','EEZ');
INSERT INTO Area VALUES('156','China','EEZ');
INSERT INTO Area VALUES('157','Taiwan','EEZ');
INSERT INTO Area VALUES('162','Australia (Christmas Isl.)','EEZ');
INSERT INTO Area VALUES('162','Christmas Isl. (Australia)','EEZ');
INSERT INTO Area VALUES('166','Australia (Cocos (Keeling) Isl.)','EEZ');
INSERT INTO Area VALUES('166','Cocos (Keeling) Isl. (Australia)','EEZ');
INSERT INTO Area VALUES('170','Colombia','EEZ');
INSERT INTO Area VALUES('174','Comoros','EEZ');
INSERT INTO Area VALUES('175','France (Mayotte)','EEZ');
INSERT INTO Area VALUES('175','Mayotte (France)','EEZ');
INSERT INTO Area VALUES('178','Congo','EEZ');
INSERT INTO Area VALUES('180','Congo (ex-Zaire)','EEZ');
INSERT INTO Area VALUES('184','Cook Isl. (New Zealand)','EEZ');
INSERT INTO Area VALUES('184','New Zealand (Cook Isl.)','EEZ');
INSERT INTO Area VALUES('188','Costa Rica','EEZ');
INSERT INTO Area VALUES('191','Croatia','EEZ');
INSERT INTO Area VALUES('192','Cuba','EEZ');
INSERT INTO Area VALUES('196','Cyprus','EEZ');
INSERT INTO Area VALUES('204','Benin','EEZ');
INSERT INTO Area VALUES('208','Denmark','EEZ');
INSERT INTO Area VALUES('212','Dominica','EEZ');
INSERT INTO Area VALUES('214','Dominican Republic','EEZ');
INSERT INTO Area VALUES('218','Ecuador','EEZ');
INSERT INTO Area VALUES('219','Ecuador (Galapagos Isl.)','EEZ');
INSERT INTO Area VALUES('219','Galapagos Isl. (Ecuador)','EEZ');
INSERT INTO Area VALUES('222','El Salvador','EEZ');
INSERT INTO Area VALUES('226','Equatorial Guinea','EEZ');
INSERT INTO Area VALUES('233','Estonia','EEZ');
INSERT INTO Area VALUES('234','Denmark (Faeroe Isl.)','EEZ');
INSERT INTO Area VALUES('234','Faeroe Isl. (Denmark)','EEZ');
INSERT INTO Area VALUES('238','Falkland Isl. (UK)','EEZ');
INSERT INTO Area VALUES('238','UK (Falkland Isl.)','EEZ');
INSERT INTO Area VALUES('239','South Georgia & Sandwich Isl.','EEZ');
INSERT INTO Area VALUES('239','UK (South Georgia & Sandwich Isl.)','EEZ');
INSERT INTO Area VALUES('242','Fiji','EEZ');
INSERT INTO Area VALUES('246','Finland','EEZ');
INSERT INTO Area VALUES('250','France','EEZ');
INSERT INTO Area VALUES('251','France (Mozambique Channel Isl.)','EEZ');
INSERT INTO Area VALUES('251','Mozambique Channel Isl. (France)','EEZ');
INSERT INTO Area VALUES('252','France (Tromelin Isl.)','EEZ');
INSERT INTO Area VALUES('252','Tromelin Isl. (France)','EEZ');
INSERT INTO Area VALUES('254','France (French Guiana)','EEZ');
INSERT INTO Area VALUES('254','French Guiana','EEZ');
INSERT INTO Area VALUES('258','France (French Polynesia)','EEZ');
INSERT INTO Area VALUES('258','French Polynesia','EEZ');
INSERT INTO Area VALUES('262','Djibouti','EEZ');
INSERT INTO Area VALUES('266','Gabon','EEZ');
INSERT INTO Area VALUES('268','Georgia','EEZ');
INSERT INTO Area VALUES('270','Gambia','EEZ');
INSERT INTO Area VALUES('274','Gaza Strip','EEZ');
INSERT INTO Area VALUES('277','Germany (North Sea)','EEZ');
INSERT INTO Area VALUES('278','Germany (Baltic Sea)','EEZ');
INSERT INTO Area VALUES('288','Ghana','EEZ');
INSERT INTO Area VALUES('292','Gibraltar (UK)','EEZ');
INSERT INTO Area VALUES('292','UK (Gibraltar)','EEZ');
INSERT INTO Area VALUES('296','Kiribati','EEZ');
INSERT INTO Area VALUES('300','Greece','EEZ');
INSERT INTO Area VALUES('304','Denmark (Greenland)','EEZ');
INSERT INTO Area VALUES('304','Greenland','EEZ');
INSERT INTO Area VALUES('308','Grenada','EEZ');
INSERT INTO Area VALUES('312','France (Guadeloupe)','EEZ');
INSERT INTO Area VALUES('312','Guadeloupe (France)','EEZ');
INSERT INTO Area VALUES('316','Guam (USA)','EEZ');
INSERT INTO Area VALUES('316','USA (Guam)','EEZ');
INSERT INTO Area VALUES('320','Guatemala','EEZ');
INSERT INTO Area VALUES('324','Guinea','EEZ');
INSERT INTO Area VALUES('328','Guyana','EEZ');
INSERT INTO Area VALUES('332','Haiti','EEZ');
INSERT INTO Area VALUES('334','Australia (Heard & McDonald Isl.)','EEZ');
INSERT INTO Area VALUES('334','Heard & McDonald Isl. (Australia)','EEZ');
INSERT INTO Area VALUES('340','Honduras','EEZ');
INSERT INTO Area VALUES('344','China Main (Hong Kong)','EEZ');
INSERT INTO Area VALUES('344','Hong Kong','EEZ');
INSERT INTO Area VALUES('352','Iceland','EEZ');
INSERT INTO Area VALUES('356','India','EEZ');
INSERT INTO Area VALUES('357','Andaman & Nicobar Isl. (India)','EEZ');
INSERT INTO Area VALUES('357','India (Andaman & Nicobar Isl.)','EEZ');
INSERT INTO Area VALUES('360','Indonesia','EEZ');
INSERT INTO Area VALUES('364','Iran','EEZ');
INSERT INTO Area VALUES('368','Iraq','EEZ');
INSERT INTO Area VALUES('372','Ireland','EEZ');
INSERT INTO Area VALUES('376','Israel','EEZ');
INSERT INTO Area VALUES('380','Italy','EEZ');
INSERT INTO Area VALUES('384','Cote d_Ivoire','EEZ');
INSERT INTO Area VALUES('388','Jamaica','EEZ');
INSERT INTO Area VALUES('392','Japan (main islands)','EEZ');
INSERT INTO Area VALUES('393','Japan (outer islands)','EEZ');
INSERT INTO Area VALUES('396','Johnston Isl. (USA)','EEZ');
INSERT INTO Area VALUES('396','USA (Johnston Isl.)','EEZ');
INSERT INTO Area VALUES('400','Jordan','EEZ');
INSERT INTO Area VALUES('404','Kenya','EEZ');
INSERT INTO Area VALUES('408','Korea (North)','EEZ');
INSERT INTO Area VALUES('410','Korea (South)','EEZ');
INSERT INTO Area VALUES('414','Kuwait','EEZ');
INSERT INTO Area VALUES('422','Lebanon','EEZ');
INSERT INTO Area VALUES('428','Latvia','EEZ');
INSERT INTO Area VALUES('430','Liberia','EEZ');
INSERT INTO Area VALUES('434','Libyan','EEZ');
INSERT INTO Area VALUES('440','Lithuania','EEZ');
INSERT INTO Area VALUES('446','China Main (Macau)','EEZ');
INSERT INTO Area VALUES('446','Macau (China)','EEZ');
INSERT INTO Area VALUES('450','Madagascar','EEZ');
INSERT INTO Area VALUES('459','Malaysia (Peninsula West)','EEZ');
INSERT INTO Area VALUES('460','Malaysia (Peninsula East)','EEZ');
INSERT INTO Area VALUES('461','Malaysia (Sabah)','EEZ');
INSERT INTO Area VALUES('462','Maldives','EEZ');
INSERT INTO Area VALUES('463','Malaysia (Sarawak)','EEZ');
INSERT INTO Area VALUES('470','Malta','EEZ');
INSERT INTO Area VALUES('474','France (Martinique)','EEZ');
INSERT INTO Area VALUES('474','Martinique (France)','EEZ');
INSERT INTO Area VALUES('478','Mauritania','EEZ');
INSERT INTO Area VALUES('480','Mauritius','EEZ');
INSERT INTO Area VALUES('484','Mexico','EEZ');
INSERT INTO Area VALUES('488','Midway Isl. (USA)','EEZ');
INSERT INTO Area VALUES('488','USA (Midway Isl.)','EEZ');
INSERT INTO Area VALUES('492','Monaco','EEZ');
INSERT INTO Area VALUES('500','Montserrat (UK)','EEZ');
INSERT INTO Area VALUES('500','UK (Montserrat)','EEZ');
INSERT INTO Area VALUES('504','Morocco','EEZ');
INSERT INTO Area VALUES('508','Mozambique','EEZ');
INSERT INTO Area VALUES('512','Oman','EEZ');
INSERT INTO Area VALUES('516','Namibia','EEZ');
INSERT INTO Area VALUES('520','Nauru','EEZ');
INSERT INTO Area VALUES('528','Netherlands','EEZ');
INSERT INTO Area VALUES('532','Netherlands (Netherlands Antilles)','EEZ');
INSERT INTO Area VALUES('532','Netherlands Antilles','EEZ');
INSERT INTO Area VALUES('533','Aruba (Netherlands)','EEZ');
INSERT INTO Area VALUES('533','Netherlands (Aruba)','EEZ');
INSERT INTO Area VALUES('540','France (New Caledonia)','EEZ');
INSERT INTO Area VALUES('540','New Caledonia (France)','EEZ');
INSERT INTO Area VALUES('548','Vanuatu','EEZ');
INSERT INTO Area VALUES('554','New Zealand','EEZ');
INSERT INTO Area VALUES('555','Kermadec Isl. (New Zealand)','EEZ');
INSERT INTO Area VALUES('555','New Zealand (Kermadec Isl.)','EEZ');
INSERT INTO Area VALUES('558','Nicaragua','EEZ');
INSERT INTO Area VALUES('566','Nigeria','EEZ');
INSERT INTO Area VALUES('570','New Zealand (Niue)','EEZ');
INSERT INTO Area VALUES('570','Niue (New Zealand)','EEZ');
INSERT INTO Area VALUES('574','Australia (Norfolk Isl.)','EEZ');
INSERT INTO Area VALUES('574','Norfolk Isl. (Australia)','EEZ');
INSERT INTO Area VALUES('578','Norway','EEZ');
INSERT INTO Area VALUES('579','Jan Mayen Isl. (Norway)','EEZ');
INSERT INTO Area VALUES('579','Norway (Jan Mayen Isl.)','EEZ');
INSERT INTO Area VALUES('580','North Marianas (USA)','EEZ');
INSERT INTO Area VALUES('580','USA (North Marianas)','EEZ');
INSERT INTO Area VALUES('583','Micronesia','EEZ');
INSERT INTO Area VALUES('584','Marshall Isl.','EEZ');
INSERT INTO Area VALUES('585','Palau','EEZ');
INSERT INTO Area VALUES('586','Pakistan','EEZ');
INSERT INTO Area VALUES('591','Panama','EEZ');
INSERT INTO Area VALUES('598','Papua New Guinea','EEZ');
INSERT INTO Area VALUES('604','Peru','EEZ');
INSERT INTO Area VALUES('608','Philippines','EEZ');
INSERT INTO Area VALUES('612','Pitcairn (UK)','EEZ');
INSERT INTO Area VALUES('612','UK (Pitcairn)','EEZ');
INSERT INTO Area VALUES('616','Poland','EEZ');
INSERT INTO Area VALUES('620','Portugal','EEZ');
INSERT INTO Area VALUES('621','Madeira Isl. (Portugal)','EEZ');
INSERT INTO Area VALUES('621','Portugal (Madeira Isl.)','EEZ');
INSERT INTO Area VALUES('622','Azores Isl. (Portugal)','EEZ');
INSERT INTO Area VALUES('622','Portugal (Azores Isl.)','EEZ');
INSERT INTO Area VALUES('624','Guinea-Bissau','EEZ');
INSERT INTO Area VALUES('626','Timor Leste','EEZ');
INSERT INTO Area VALUES('630','Puerto Rico (USA)','EEZ');
INSERT INTO Area VALUES('630','USA (Puerto Rico)','EEZ');
INSERT INTO Area VALUES('634','Qatar','EEZ');
INSERT INTO Area VALUES('638','France (Reunion)','EEZ');
INSERT INTO Area VALUES('638','Reunion (France)','EEZ');
INSERT INTO Area VALUES('642','Romania','EEZ');
INSERT INTO Area VALUES('644','Russian Fed (Asia)','EEZ');
INSERT INTO Area VALUES('645','Russian Fed (Baltic Sea)','EEZ');
INSERT INTO Area VALUES('647','Russian Fed (Barents Sea)','EEZ');
INSERT INTO Area VALUES('654','Saint Helena (UK)','EEZ');
INSERT INTO Area VALUES('654','UK (Saint Helena)','EEZ');
INSERT INTO Area VALUES('659','Saint Kitts & Nevis','EEZ');
INSERT INTO Area VALUES('660','Anguilla (UK)','EEZ');
INSERT INTO Area VALUES('660','UK (Anguilla)','EEZ');
INSERT INTO Area VALUES('662','Saint Lucia','EEZ');
INSERT INTO Area VALUES('666','France (Saint Pierre & Miquelon)','EEZ');
INSERT INTO Area VALUES('666','Saint Pierre & Miquelon (France)','EEZ');
INSERT INTO Area VALUES('670','Saint Vincent & the Grenadines','EEZ');
INSERT INTO Area VALUES('678','Sao Tome & Principe','EEZ');
INSERT INTO Area VALUES('683','Saudi Arabia (Red Sea)','EEZ');
INSERT INTO Area VALUES('684','Saudi Arabia (Persian Gulf)','EEZ');
INSERT INTO Area VALUES('686','Senegal','EEZ');
INSERT INTO Area VALUES('690','Seychelles','EEZ');
INSERT INTO Area VALUES('694','Sierra Leone','EEZ');
INSERT INTO Area VALUES('702','Singapore','EEZ');
INSERT INTO Area VALUES('704','Viet Nam','EEZ');
INSERT INTO Area VALUES('705','Slovenia','EEZ');
INSERT INTO Area VALUES('706','Somalia','EEZ');
INSERT INTO Area VALUES('710','South Africa','EEZ');
INSERT INTO Area VALUES('711','Prince Edward Isl. (South Africa)','EEZ');
INSERT INTO Area VALUES('711','South Africa (Prince Edward Isl.)','EEZ');
INSERT INTO Area VALUES('723','Canary Isl. (Spain)','EEZ');
INSERT INTO Area VALUES('723','Spain (Canary Isl.)','EEZ');
INSERT INTO Area VALUES('724','Spain','EEZ');
INSERT INTO Area VALUES('732','Morocco (Western Sahara)','EEZ');
INSERT INTO Area VALUES('732','Western Sahara (Morocco)','EEZ');
INSERT INTO Area VALUES('736','Sudan','EEZ');
INSERT INTO Area VALUES('740','Suriname','EEZ');
INSERT INTO Area VALUES('744','Norway (Svalbard Isl.)','EEZ');
INSERT INTO Area VALUES('744','Svalbard Isl. (Norway)','EEZ');
INSERT INTO Area VALUES('752','Sweden','EEZ');
INSERT INTO Area VALUES('760','Syrian Arab Republic','EEZ');
INSERT INTO Area VALUES('764','Thailand','EEZ');
INSERT INTO Area VALUES('768','Togo','EEZ');
INSERT INTO Area VALUES('772','New Zealand (Tokelau)','EEZ');
INSERT INTO Area VALUES('772','Tokelau (New Zealand)','EEZ');
INSERT INTO Area VALUES('776','Tonga','EEZ');
INSERT INTO Area VALUES('780','Trinidad & Tobago','EEZ');
INSERT INTO Area VALUES('784','United Arab Emirates','EEZ');
INSERT INTO Area VALUES('788','Tunisia','EEZ');
INSERT INTO Area VALUES('793','Turkey (Mediterranean Sea)','EEZ');
INSERT INTO Area VALUES('794','Turkey (Black Sea)','EEZ');
INSERT INTO Area VALUES('796','Turks & Caicos Isl. (UK)','EEZ');
INSERT INTO Area VALUES('796','UK (Turks & Caicos Isl.)','EEZ');
INSERT INTO Area VALUES('798','Tuvalu','EEZ');
INSERT INTO Area VALUES('804','Ukraine','EEZ');
INSERT INTO Area VALUES('818','Egypt','EEZ');
INSERT INTO Area VALUES('826','United Kingdom','EEZ');
INSERT INTO Area VALUES('830','Channel Isl. (UK)','EEZ');
INSERT INTO Area VALUES('830','UK (Channel Isl.)','EEZ');
INSERT INTO Area VALUES('834','Tanzania','EEZ');
INSERT INTO Area VALUES('840','USA (contiguous states)','EEZ');
INSERT INTO Area VALUES('841','Alaska (USA)','EEZ');
INSERT INTO Area VALUES('841','USA (Alaska)','EEZ');
INSERT INTO Area VALUES('842','Hawaii (USA)','EEZ');
INSERT INTO Area VALUES('842','USA (Hawaii)','EEZ');
INSERT INTO Area VALUES('843','Navassa Isl. (USA)','EEZ');
INSERT INTO Area VALUES('843','USA (Navassa Isl.)','EEZ');
INSERT INTO Area VALUES('844','Palmyra Isl. & Kingman Reef','EEZ');
INSERT INTO Area VALUES('844','USA (Palmyra Isl. & Kingman Reef)','EEZ');
INSERT INTO Area VALUES('845','Jarvis Isl. (USA)','EEZ');
INSERT INTO Area VALUES('845','USA (Jarvis Isl.)','EEZ');
INSERT INTO Area VALUES('846','Baker & Howland Isl. (USA)','EEZ');
INSERT INTO Area VALUES('846','USA (Baker & Howland Isl.)','EEZ');
INSERT INTO Area VALUES('850','US Virgin Isl.','EEZ');
INSERT INTO Area VALUES('850','USA (US Virgin Isl.)','EEZ');
INSERT INTO Area VALUES('855','Ascension Isl. (UK)','EEZ');
INSERT INTO Area VALUES('855','St Helena (Ascension Isl.)','EEZ');
INSERT INTO Area VALUES('856','St Helena (Tristan da Cunha Isl.)','EEZ');
INSERT INTO Area VALUES('856','Tristan da Cunha Isl. (UK)','EEZ');
INSERT INTO Area VALUES('858','Uruguay','EEZ');
INSERT INTO Area VALUES('862','Venezuela','EEZ');
INSERT INTO Area VALUES('872','USA (Wake Isl.)','EEZ');
INSERT INTO Area VALUES('872','Wake Isl. (USA)','EEZ');
INSERT INTO Area VALUES('876','France (Wallis & Futuna Isl.)','EEZ');
INSERT INTO Area VALUES('876','Wallis & Futuna Isl. (France)','EEZ');
INSERT INTO Area VALUES('882','Samoa','EEZ');
INSERT INTO Area VALUES('887','Yemen','EEZ');
INSERT INTO Area VALUES('891','Montenegro','EEZ');
INSERT INTO Area VALUES('895','France (St Paul & Amsterdam Isl.)','EEZ');
INSERT INTO Area VALUES('895','St Paul & Amsterdam Isl. (France)','EEZ');
INSERT INTO Area VALUES('896','Crozet Isl. (France)','EEZ');
INSERT INTO Area VALUES('896','France (Crozet Isl.)','EEZ');
INSERT INTO Area VALUES('897','France (Kerguelen Isl.)','EEZ');
INSERT INTO Area VALUES('897','Kerguelen Isl. (France)','EEZ');
INSERT INTO Area VALUES('898','Clipperton Isl. (France)','EEZ');
INSERT INTO Area VALUES('898','France (Clipperton Isl.)','EEZ');

INSERT INTO Area VALUES('1','East Bering Sea','LME');
INSERT INTO Area VALUES('2','Gulf of Alaska','LME');
INSERT INTO Area VALUES('3','California Current','LME');
INSERT INTO Area VALUES('4','Gulf of California','LME');
INSERT INTO Area VALUES('5','Gulf of Mexico','LME');
INSERT INTO Area VALUES('6','Southeast U.S. Continental Shelf','LME');
INSERT INTO Area VALUES('7','Northeast U.S. Continental Shelf','LME');
INSERT INTO Area VALUES('8','Scotian Shelf','LME');
INSERT INTO Area VALUES('9','Newfoundland-Labrador Shelf','LME');
INSERT INTO Area VALUES('10','Insular Pacific-Hawaiian','LME');
INSERT INTO Area VALUES('11','Pacific Central-American Coastal','LME');
INSERT INTO Area VALUES('12','Caribbean Sea','LME');
INSERT INTO Area VALUES('13','Humboldt Current','LME');
INSERT INTO Area VALUES('14','Patagonian Shelf','LME');
INSERT INTO Area VALUES('15','South Brazil Shelf','LME');
INSERT INTO Area VALUES('16','East Brazil Shelf','LME');
INSERT INTO Area VALUES('17','North Brazil Shelf','LME');
INSERT INTO Area VALUES('18','West Greenland Shelf','LME');
INSERT INTO Area VALUES('19','Iceland Shelf/Sea','LME');
INSERT INTO Area VALUES('20','Barents Sea','LME');
INSERT INTO Area VALUES('21','Norwegian Sea','LME');
INSERT INTO Area VALUES('22','North Sea','LME');
INSERT INTO Area VALUES('23','Baltic Sea','LME');
INSERT INTO Area VALUES('24','Celtic-Biscay Shelf','LME');
INSERT INTO Area VALUES('25','Iberian Coastal','LME');
INSERT INTO Area VALUES('26','Mediterranean Sea','LME');
INSERT INTO Area VALUES('27','Canary Current','LME');
INSERT INTO Area VALUES('28','Guinea Current','LME');
INSERT INTO Area VALUES('29','Benguela Current','LME');
INSERT INTO Area VALUES('30','Agulhas Current','LME');
INSERT INTO Area VALUES('31','Somali Coastal Current','LME');
INSERT INTO Area VALUES('32','Arabian Sea','LME');
INSERT INTO Area VALUES('33','Red Sea','LME');
INSERT INTO Area VALUES('34','Bay of Bengal','LME');
INSERT INTO Area VALUES('35','Gulf of Thailand','LME');
INSERT INTO Area VALUES('36','South China Sea','LME');
INSERT INTO Area VALUES('37','Sulu-Celebes Sea','LME');
INSERT INTO Area VALUES('38','Indonesian Sea','LME');
INSERT INTO Area VALUES('39','North Australian Shelf','LME');
INSERT INTO Area VALUES('40','Northeast Australian Shelf','LME');
INSERT INTO Area VALUES('41','East Central Australian Shelf','LME');
INSERT INTO Area VALUES('42','Southeast Australian Shelf','LME');
INSERT INTO Area VALUES('43','Southwest Australian Shelf','LME');
INSERT INTO Area VALUES('44','West Central Australian Shelf','LME');
INSERT INTO Area VALUES('45','Northwest Australian Shelf','LME');
INSERT INTO Area VALUES('46','New Zealand Shelf','LME');
INSERT INTO Area VALUES('47','East China Sea','LME');
INSERT INTO Area VALUES('48','Yellow Sea','LME');
INSERT INTO Area VALUES('49','Kuroshio Current','LME');
INSERT INTO Area VALUES('50','Sea of Japan/East Sea','LME');
INSERT INTO Area VALUES('51','Oyashio Current','LME');
INSERT INTO Area VALUES('52','Okhotsk Sea','LME');
INSERT INTO Area VALUES('53','West Bering Sea','LME');
INSERT INTO Area VALUES('54','Chukchi Sea','LME');
INSERT INTO Area VALUES('55','Beaufort Sea','LME');
INSERT INTO Area VALUES('56','East Siberian Sea','LME');
INSERT INTO Area VALUES('57','Laptev Sea','LME');
INSERT INTO Area VALUES('58','Kara Sea','LME');
INSERT INTO Area VALUES('59','Greenland Sea','LME');
INSERT INTO Area VALUES('60','Faroe Plateau','LME');
INSERT INTO Area VALUES('61','Antarctic','LME');
INSERT INTO Area VALUES('62','Black Sea','LME');
INSERT INTO Area VALUES('63','Hudson Bay','LME');
INSERT INTO Area VALUES('64','Arctic Ocean','LME');
INSERT INTO Area VALUES('65','Arctic Archipelago','LME');
INSERT INTO Area VALUES('66','Baffin Bay/Davis Straight','LME');


