#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/massi/portal/gwt-linux-1.5.3/gwt-user.jar:/home/massi/portal/gwt-linux-1.5.3/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.gcube.portlets.d4sreporting.common.Reporting/Reporting.html;
