package org.gcube.application.aquamaps.aquamapsservice.stubs.fw.fields;

public enum HspenFields {
	lifestage,
	faoareas ,
	faoareasref,
	faocomplete,
	nmostlat,
	smostlat,
	wmostlong,
	emostlong,
	lme,
	depthmin,
	depthmax,
	depthprefmin,
	depthprefmax,
	meandepth    ,
	pelagic      ,
	depthref     ,
	tempmin      ,
	tempmax      ,
	tempprefmin  ,
	tempprefmax  ,
	tempref      ,
	salinitymin  ,
	salinitymax  ,
	salinityprefmin,
	salinityprefmax,
	salinityref,
	primprodmin,
	primprodmax,
	primprodprefmin,
	primprodprefmax, 
	primprodprefref,
	iceconmin      ,
	iceconmax,
	iceconprefmin,
	iceconprefmax,
	iceconref    ,
	landdistmin  ,
	landdistmax   ,
	landdistprefmin,
	landdistprefmax,
	landdistref,
	landdistyn, //added since march 2011
	remark,
	datecreated,
	datemodified,
	expert,
	dateexpert,
	envelope,
	mapdata,
	effort,
	layer,
	usepoints,
	rank,

	
}
