package org.gcube.portlets.user.databasesmanager.client.datamodel;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;

//class that allows to wrap output generated by the servlet
import com.extjs.gxt.ui.client.data.BaseModelData;

public class GeneralOutputFromServlet extends BaseModelData implements
		Serializable {

	private static final long serialVersionUID = 1L;

	private List<FileModel> listOutput;
	private LinkedHashMap<String, FileModel> mapOutput;

	public GeneralOutputFromServlet() {

	}

	public GeneralOutputFromServlet(List<FileModel> data) {
		set("listOutput", data);
	}
	
	public GeneralOutputFromServlet(LinkedHashMap<String, FileModel> data) {
		set("mapOutput", data);
	}

	public List<FileModel> getListOutput(){
		return get("listOutput");
	}
	public LinkedHashMap<String, FileModel> getMapOutput(){
		return get("mapOutput");
	}
}
