compile:
	ant -Dresultset.library.location=../Dependencies/ResultSetClientLibrary -Dresultsetservice.stubs.location=../Dependencies/ResultSetClientLibrary -Dglobus.location=${GLOBUS_LOCATION} -Dresultsetservice.service.location=../Dependencies/ResultSetClientLibrary
jar:
	ant jar -Dresultset.library.location=../Dependencies/ResultSetClientLibrary -Dresultsetservice.stubs.location=../Dependencies/ResultSetClientLibrary -Dglobus.location=${GLOBUS_LOCATION} -Dresultsetservice.service.location=../Dependencies/ResultSetClientLibrary
javadoc:
	ant javadoc -Dresultset.library.location=../Dependencies/ResultSetClientLibrary -Dresultsetservice.stubs.location=../Dependencies/ResultSetClientLibrary -Dresultsetservice.service.location=../Dependencies/ResultSetClientLibrary
clean:
	ant clean
