<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GCUBETypes"
    targetNamespace="http://gcube-system.org/namespaces/common/core/types"
    xmlns:tns="http://gcube-system.org/namespaces/common/core/types"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing" 
	elementFormDefault="qualified" attributeFormDefault="unqualified">
    
<!--============================================================

                      T Y P E S
                      
  ============================================================-->
<types>
<xs:schema 
   targetNamespace="http://gcube-system.org/namespaces/common/core/types"
   xmlns:tns="http://gcube-system.org/namespaces/common/core/types">

	<xs:import namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing" schemaLocation="../../../../ws/addressing/WS-Addressing.xsd" />
	<xs:include schemaLocation="GCUBETypes.xsd" />

</xs:schema>
</types>

</definitions>
