 <Resource>
   {$GHNs/ID}
   {$GHNs/Profile/GHNDescription/Name}
   {$GHNs/Profile/GHNDescription/Status}
   {$GHNs/Profile/GHNDescription/Type}
   {$GHNs/Profile/Site/Location}
   {$GHNs/Profile/Site/Domain}
   <IPAddress>{$GHNs/Profile/GHNDescription/NetworkAdapter/@IPAddress/string()}</IPAddress>
   <Scopes>{$scopes}</Scopes>
   <AllocatedRI>{count($RIinstalled)}</AllocatedRI>
   {$GHNs/Profile/GHNDescription/LastUpdate}
   <Actions>APPLY_GHN_MOVE_TO_UNREACHABLE</Actions>
 </Resource>