package org.gcube.portlets.widgets.applicationnews.client;

import org.gcube.portal.databook.shared.ImageType;
import org.gcube.portlets.widgets.applicationnews.shared.LinkPreview;

import com.google.gwt.core.client.EntryPoint;
import com.google.gwt.user.client.ui.RootPanel;

/**
 *	gCube Application News Widget is a GWT Widget that can be used for posting News from your gCube Portlet to users News Feed.
 *	 	(belonging to the VRE where your portlet is deployed). Please note that your Application Profile must be added to the 
 *	 	Infrastructure Information System to use this widget, instructions for creating it can be found in the ASL Social wiki page.
 *
 *  @see <a href="http://gcube.wiki.gcube-system.org/gcube/index.php/Publish_App_News_in_User_Feeds_(Social_Portal)">Documentation</a>
 */
public class ApplicationNews_Widget implements EntryPoint {

	public void onModuleLoad() {
		//sample();
	}

	private void sample() {
		LinkPreview lp = new LinkPreview("Thunnus obesus - Continental Asia View", "The Thunnus alalunga Species Distribution Map for the Asia area is available, " +
				"fake AquaMaps exploits several computational backends: a single multi-core server, " +
				"distributed services offered by the D4science infrastructure and cloud resources.", 
				"http://dl.dropbox.com/u/15737233/ContinentViewAsia.jpg", ImageType.JPG);
		RootPanel.get().add(new ApplicationNewsButton("org.cotrix.web", "A new Fake Species Distribution Map was generated by Mickey Mouse", "id=12345", lp));
	}
}
