package org.gcube.application.aquamaps.aquamapsservice.stubs.fw.fields;

public enum HCAF_SFields {

	csquarecode   ,
	loiczid       ,
	nlimit        ,
	slimit        ,
	wlimit        ,
	elimit        ,
	centerlat     ,
	centerlong    ,
	cellarea      ,
	oceanarea     ,
	celltype      ,
	pwater        ,
	faoaream      ,
	faoareain     ,
	countrymain   ,
	countrysecond ,
	countrythird  ,
	eezfirst      ,
	eezsecond     ,
	eezthird      ,
	eezall        ,
	eezremark     ,
	lme           ,
	oceanbasin    ,
	longhurst     ,
	islandsno     ,
	area0_20      ,
	area20_40     ,
	area40_60     ,
	area60_80     ,
	area80_100    ,
	areabelow100  ,
	elevationmin  ,
	elevationmax  ,
	elevationmean ,
	elevationsd   ,
	waveheight    ,
	tidalrange    ,
	landdist      ,
	shelf        ,
	slope       ,
	abyssal    ,
	coral     ,
	estuary  ,
	seagrass,
	seamount,
	

	
	
}
