package org.gcube.portlets.user.databasesmanager.client.events;

public enum EventsTypeEnum {
	SELECTED_ITEM_EVENT,
	SUBMIT_QUERY_EVENT,
	SHOW_CREATE_TABLE_EVENT,
	SAMPLING_EVENT,
	SMART_SAMPLING_EVENT,
	RANDOM_SAMPLING_EVENT,
	LOAD_TABLES_EVENT,
	SELECTED_TABLE_EVENT,
	CANCEL_EXECUTION_QUERY,
	REFRESH_DATA;
	}