<?xml version="1.0" encoding="UTF-8"?>

<definitions name="Factory"
	targetNamespace="http://gcube-system.org/namespaces/datatransfer/scheduler/datatransferscheduler"
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://gcube-system.org/namespaces/datatransfer/scheduler/datatransferscheduler"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:provider="http://gcube-system.org/namespaces/common/core/porttypes/GCUBEProvider"
    xmlns:wsrp="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.xsd"
    xmlns:wsrpw="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
    xmlns:wsntw="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
    xmlns:corefaults="http://gcube-system.org/namespaces/common/core/faults"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing"	
	xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<import
		namespace="http://gcube-system.org/namespaces/common/core/porttypes/GCUBEProvider"
		location="../gcube/common/core/providers/GCUBEProvider.wsdl" />


	<wsdl:import
		namespace="http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceProperties-1.2-draft-01.wsdl"
		location="../wsrf/properties/WS-ResourceProperties.wsdl" />

	<wsdl:import
		namespace="http://docs.oasis-open.org/wsn/2004/06/wsn-WS-BaseNotification-1.2-draft-01.wsdl"
		location="../wsrf/notification/WS-BaseN.wsdl" />


	<wsdl:import namespace="http://gcube-system.org/namespaces/common/core/faults"
		location="../gcube/common/core/faults/GCUBEFaults.wsdl" />

	<types>
		<xsd:schema
			targetNamespace="http://gcube-system.org/namespaces/datatransfer/scheduler/datatransferscheduler"
			xmlns:tns="http://gcube-system.org/namespaces/datatransfer/scheduler/datatransferscheduler"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns:corefaults="http://gcube-system.org/namespaces/common/core/faults">
    
		 <xsd:import namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing" schemaLocation="../ws/addressing/WS-Addressing.xsd" />
	
  		<xsd:element name="create" type="xsd:string" />		
		<xsd:element name="createResponse" type="wsa:EndpointReferenceType"/>
	</xsd:schema>
	</types>

	<message name="createInputMessage">
		<part name="request" element="tns:create"/>
	</message>
	<message name="createOutputMessage">
		<part name="response" element="tns:createResponse"/>
	</message>

	<portType name="FactoryPortType">
	
		<operation name="create">
			<input message="tns:createInputMessage"/>
			<output message="tns:createOutputMessage"/>
		<fault name="fault" message="corefaults:GCUBEFaultMessage"></fault>
		
	</operation>
	
	</portType>

</definitions>
