function ColumnWidget(){var S='',Ab='" for "gwt:onLoadErrorFn"',yb='" for "gwt:onPropertyErrorFn"',lb='"><\/script>',ab='#',pc='.cache.html',cb='/',ob='//',oc=':',sb='::',xc='<script defer="defer">ColumnWidget.onInjectionDone(\'ColumnWidget\')<\/script>',kb='<script id="',vb='=',bb='?',xb='Bad handler "',T='ColumnWidget',hb='ColumnWidget.nocache.js',rb='ColumnWidget::',wc='DOMContentLoaded',nc="GWT module 'ColumnWidget' may need to be (re)compiled",mb='SCRIPT',jb='__gwt_marker_ColumnWidget',$b='adobeair',_b='air',nb='base',fb='baseUrl',W='begin',V='bootstrap',Gb='chrome',eb='clear.cache.gif',ub='content',_='end',Wb='gecko',Yb='gecko1_8',Zb='gecko1_9',X='gwt.codesvr=',Y='gwt.hosted=',Z='gwt.hybrid',qc='gwt/standard/standard.css',zb='gwt:onLoadErrorFn',wb='gwt:onPropertyErrorFn',tb='gwt:property',Fb='gxt.user.agent',vc='head',lc='hosted.html?ColumnWidget',uc='href',Jb='ie10',Pb='ie6',Nb='ie7',Lb='ie8',Kb='ie9',Bb='iframe',db='img',Cb="javascript:''",rc='link',hc='linux',kc='loadExternalRefs',gc='mac',fc='mac os x',ec='macintosh',pb='meta',Eb='moduleRequested',$='moduleStartup',Ib='msie',Ob='msie 6',Mb='msie 7',qb='name',Hb='opera',Db='position:absolute;width:0;height:0;border:none',sc='rel',Xb='rv:1.8',Qb='safari',Sb='safari3',Ub='safari4',Vb='safari5',gb='script',mc='selectingPermutation',U='startup',tc='stylesheet',ib='undefined',cc='unknown',ac='user.agent',dc='user.agent.os',Rb='version/3',Tb='version/4',bc='webkit',jc='win32',ic='windows';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=S,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:V,millis:(new Date).getTime(),type:W});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(X)!=-1||(c.indexOf(Y)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(Z)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(T);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return K(a)}}ColumnWidget=null;c.gwtOnLoad(C,T,t,B);o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:$,millis:(new Date).getTime(),type:_})}}
function H(){function e(a){var b=a.lastIndexOf(ab);if(b==-1){b=a.length}var c=a.indexOf(bb);if(c==-1){c=a.length}var d=a.lastIndexOf(cb,Math.min(c,b));return d>=0?a.substring(0,d+1):S}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(db);b.src=a+eb;a=e(b.src)}return a}
function g(){var a=J(fb);if(a!=null){return a}return S}
function h(){var a=n.getElementsByTagName(gb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(hb)!=-1){return e(a[b].src)}}return S}
function i(){var a;if(typeof isBodyLoaded==ib||!isBodyLoaded()){var b=jb;var c;n.write(kb+b+lb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=mb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return S}
function j(){var a=n.getElementsByTagName(nb);if(a.length>0){return a[a.length-1].href}return S}
function k(){var a=n.location;return a.href==a.protocol+ob+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==S){l=h()}if(l==S){l=i()}if(l==S){l=j()}if(l==S&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(pb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(qb),g;if(f){f=f.replace(rb,S);if(f.indexOf(sb)>=0){continue}if(f==tb){g=e.getAttribute(ub);if(g){var h,i=g.indexOf(vb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=S}u[f]=h}}else if(f==wb){g=e.getAttribute(ub);if(g){try{D=eval(g)}catch(a){alert(xb+g+yb)}}}else if(f==zb){g=e.getAttribute(ub);if(g){try{C=eval(g)}catch(a){alert(xb+g+Ab)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var L;function M(){if(!L){L=true;var a=n.createElement(Bb);a.src=Cb;a.id=T;a.style.cssText=Db;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:$,millis:(new Date).getTime(),type:Eb});a.contentWindow.location.replace(t+O)}}
w[Fb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Gb)!=-1)return Gb;if(a.indexOf(Hb)!=-1)return Hb;if(a.indexOf(Ib)!=-1){if(n.documentMode>=10)return Jb;if(n.documentMode>=9)return Kb;if(n.documentMode>=8)return Lb;if(a.indexOf(Mb)!=-1)return Nb;if(a.indexOf(Ob)!=-1)return Pb;return Jb}if(a.indexOf(Qb)!=-1){if(a.indexOf(Rb)!=-1)return Sb;if(a.indexOf(Tb)!=-1)return Ub;return Vb}if(a.indexOf(Wb)!=-1){if(a.indexOf(Xb)!=-1)return Yb;return Zb}if(a.indexOf($b)!=-1)return _b;return null};v[Fb]={air:0,chrome:1,gecko1_8:2,gecko1_9:3,ie10:4,ie8:5,ie9:6,safari3:7,safari4:8,safari5:9};w[ac]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(bc)!=-1}())return Qb;if(function(){return b.indexOf(Ib)!=-1&&n.documentMode>=10}())return Jb;if(function(){return b.indexOf(Ib)!=-1&&n.documentMode>=9}())return Kb;if(function(){return b.indexOf(Ib)!=-1&&n.documentMode>=8}())return Lb;if(function(){return b.indexOf(Wb)!=-1}())return Yb;return cc};v[ac]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};w[dc]=function(){var a=m.navigator.userAgent.toLowerCase();if(a.indexOf(ec)!=-1||a.indexOf(fc)!=-1){return gc}if(a.indexOf(hc)!=-1){return hc}if(a.indexOf(ic)!=-1||a.indexOf(jc)!=-1){return ic}return cc};v[dc]={linux:0,mac:1,unknown:2,windows:3};ColumnWidget.onScriptLoad=function(){if(L){r=true;G()}};ColumnWidget.onInjectionDone=function(){q=true;o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:kc,millis:(new Date).getTime(),type:_});G()};I();H();var N;var O;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(T))){m.location.reload();return}O=lc;N=S}o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:V,millis:(new Date).getTime(),type:mc});if(!F()){try{alert(nc);return;var P=N.indexOf(oc);if(P!=-1){B=Number(N.substring(P+1));N=N.substring(0,P)}O=N+pc}catch(a){return}}var Q;function R(){if(!s){s=true;if(!__gwt_stylesLoaded[qc]){var a=n.createElement(rc);__gwt_stylesLoaded[qc]=a;a.setAttribute(sc,tc);a.setAttribute(uc,t+qc);n.getElementsByTagName(vc)[0].appendChild(a)}G();if(n.removeEventListener){n.removeEventListener(wc,R,false)}if(Q){clearInterval(Q)}}}
if(n.addEventListener){n.addEventListener(wc,function(){M();R()},false)}var Q=setInterval(function(){if(/loaded|complete/.test(n.readyState)){M();R()}},50);o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:V,millis:(new Date).getTime(),type:_});o&&o({moduleName:T,sessionId:p,subSystem:U,evtGroup:kc,millis:(new Date).getTime(),type:W});n.write(xc)}
ColumnWidget();